/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as RecruiterIndexRouteImport } from './routes/recruiter.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentResumeAnalyzerRouteImport } from './routes/student.resume-analyzer'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as RecruiterQuestionsRouteImport } from './routes/recruiter.questions'
import { Route as RecruiterOffersRouteImport } from './routes/recruiter.offers'
import { Route as RecruiterJobsRouteImport } from './routes/recruiter.jobs'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterIndexRoute = RecruiterIndexRouteImport.update({
  id: '/recruiter/',
  path: '/recruiter/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentResumeAnalyzerRoute = StudentResumeAnalyzerRouteImport.update({
  id: '/student/resume-analyzer',
  path: '/student/resume-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterQuestionsRoute = RecruiterQuestionsRouteImport.update({
  id: '/recruiter/questions',
  path: '/recruiter/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterOffersRoute = RecruiterOffersRouteImport.update({
  id: '/recruiter/offers',
  path: '/recruiter/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterJobsRoute = RecruiterJobsRouteImport.update({
  id: '/recruiter/jobs',
  path: '/recruiter/jobs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/interviews': typeof InterviewsRoute
  '/jobs': typeof JobsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/recruiter/jobs': typeof RecruiterJobsRoute
  '/recruiter/offers': typeof RecruiterOffersRoute
  '/recruiter/questions': typeof RecruiterQuestionsRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/student/resume-analyzer': typeof StudentResumeAnalyzerRoute
  '/admin/': typeof AdminIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/interviews': typeof InterviewsRoute
  '/jobs': typeof JobsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/recruiter/jobs': typeof RecruiterJobsRoute
  '/recruiter/offers': typeof RecruiterOffersRoute
  '/recruiter/questions': typeof RecruiterQuestionsRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/student/resume-analyzer': typeof StudentResumeAnalyzerRoute
  '/admin': typeof AdminIndexRoute
  '/recruiter': typeof RecruiterIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/applications': typeof ApplicationsRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/interviews': typeof InterviewsRoute
  '/jobs': typeof JobsRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/recruiter/jobs': typeof RecruiterJobsRoute
  '/recruiter/offers': typeof RecruiterOffersRoute
  '/recruiter/questions': typeof RecruiterQuestionsRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/student/resume-analyzer': typeof StudentResumeAnalyzerRoute
  '/admin/': typeof AdminIndexRoute
  '/recruiter/': typeof RecruiterIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/applications'
    | '/auth'
    | '/chat'
    | '/interviews'
    | '/jobs'
    | '/profile'
    | '/settings'
    | '/stats'
    | '/recruiter/jobs'
    | '/recruiter/offers'
    | '/recruiter/questions'
    | '/room/$roomId'
    | '/student/resume-analyzer'
    | '/admin/'
    | '/recruiter/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/applications'
    | '/auth'
    | '/chat'
    | '/interviews'
    | '/jobs'
    | '/profile'
    | '/settings'
    | '/stats'
    | '/recruiter/jobs'
    | '/recruiter/offers'
    | '/recruiter/questions'
    | '/room/$roomId'
    | '/student/resume-analyzer'
    | '/admin'
    | '/recruiter'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/applications'
    | '/auth'
    | '/chat'
    | '/interviews'
    | '/jobs'
    | '/profile'
    | '/settings'
    | '/stats'
    | '/recruiter/jobs'
    | '/recruiter/offers'
    | '/recruiter/questions'
    | '/room/$roomId'
    | '/student/resume-analyzer'
    | '/admin/'
    | '/recruiter/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ApplicationsRoute: typeof ApplicationsRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  InterviewsRoute: typeof InterviewsRoute
  JobsRoute: typeof JobsRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  RecruiterJobsRoute: typeof RecruiterJobsRoute
  RecruiterOffersRoute: typeof RecruiterOffersRoute
  RecruiterQuestionsRoute: typeof RecruiterQuestionsRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  StudentResumeAnalyzerRoute: typeof StudentResumeAnalyzerRoute
  AdminIndexRoute: typeof AdminIndexRoute
  RecruiterIndexRoute: typeof RecruiterIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/': {
      id: '/recruiter/'
      path: '/recruiter'
      fullPath: '/recruiter/'
      preLoaderRoute: typeof RecruiterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/resume-analyzer': {
      id: '/student/resume-analyzer'
      path: '/student/resume-analyzer'
      fullPath: '/student/resume-analyzer'
      preLoaderRoute: typeof StudentResumeAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/questions': {
      id: '/recruiter/questions'
      path: '/recruiter/questions'
      fullPath: '/recruiter/questions'
      preLoaderRoute: typeof RecruiterQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/offers': {
      id: '/recruiter/offers'
      path: '/recruiter/offers'
      fullPath: '/recruiter/offers'
      preLoaderRoute: typeof RecruiterOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter/jobs': {
      id: '/recruiter/jobs'
      path: '/recruiter/jobs'
      fullPath: '/recruiter/jobs'
      preLoaderRoute: typeof RecruiterJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ApplicationsRoute: ApplicationsRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  InterviewsRoute: InterviewsRoute,
  JobsRoute: JobsRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  RecruiterJobsRoute: RecruiterJobsRoute,
  RecruiterOffersRoute: RecruiterOffersRoute,
  RecruiterQuestionsRoute: RecruiterQuestionsRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  StudentResumeAnalyzerRoute: StudentResumeAnalyzerRoute,
  AdminIndexRoute: AdminIndexRoute,
  RecruiterIndexRoute: RecruiterIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
